apiVersion: v1
kind: Pod
metadata:
  name: network-demo
spec:
  restartPolicy: Never
  containers:
    - name: server-container
      image: python
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Server starting on port 8080..."
          python -m http.server 8080
    - name: client-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "Client fetching from http://localhost:8080..."
            wget -qO- http://localhost:8080
            sleep 5
          done
