apiVersion: v1
kind: Pod
metadata:
  name: user-namespace-demo
spec:
  restartPolicy: Never
  containers:
    - name: server-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Server running as:"
          whoami
          id
          sleep infinity

    - name: client-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          sleep 5
          echo "Client running as:"
          whoami
          id
