apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: mount-html
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: update-html
    image: busybox
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
